-/- Auto-generated by Physics/Python/emit_bsd_ap_table_strict.py
   Source JSON: /home/luke-miller/Desktop/Theorem/Clay/Riemann/Phase_2/data/bsd_ap_table.json
   Generated: 2025-09-03T12:50:13.423207 UTC
   STRICT MODE: the emitter failed if any entry was not an integer (or integer-string).
   DO NOT EDIT BY HAND — re-run the emitter to regenerate.
-/

import Mathlib.Data.Int.Basic

namespace Physics
namespace BSD

def ap_table : List Int := [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53]

end BSD
end Physics
